sudo: false
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
script: npm run ci
os:
  - linux
  - osx
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=0e2d67512c52548873f90eb782b4467621eaa94ee7b65a130cc572dc8220adff